### ISSUE TITLE
Code Formatter not working (VSCode)

### ISSUE THREAD

**Issue by cshenton** [DanielGavin/ols#117]
Code formatting isn't working for me. Odin version:

```
        Odin: dev-2022-07-nightly:1676c643
        OS:   Windows 10 Home Basic (version: 21H2), build 19044.1766
        CPU:  AMD Ryzen 9 5900HS with Radeon Graphics
        RAM:  32160 MiB
```

On loading the extension (opening/reloading VSCode) I get the following console output:

```bash
[Error - 5:25:42 pm] error in parse file for indexing C:/Program Files/odin-windows-amd64-dev-2022-06/core/builtin/builtin.odin
[Error - 5:25:42 pm] error in parse file for indexing C:/Program Files/odin-windows-amd64-dev-2022-06/core/intrinsics/intrinsics.odin
```

When I request a document format with `alt-shift-f` I get the following output and the document fails to format

```bash
[Info  - 5:26:26 pm] Connection to server got closed. Server will restart.
[Error - 5:26:26 pm] Request textDocument/formatting failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-jsonrpc\lib\common\connection.js:1105:27)
	at Object.dispose (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-languageclient\lib\common\client.js:163:35)
	at LanguageClient.handleConnectionClosed (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-languageclient\lib\common\client.js:2665:42)
	at LanguageClient.handleConnectionClosed (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-languageclient\lib\node\main.js:173:15)
	at closeHandler (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-languageclient\lib\common\client.js:2652:18)
	at CallbackList.invoke (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at closeHandler (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-jsonrpc\lib\common\connection.js:272:26)
	at CallbackList.invoke (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
	at Emitter.fire (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
	at StreamMessageReader.fireClose (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-jsonrpc\lib\common\messageReader.js:40:27)
	at Socket.<anonymous> (c:\Users\username\.vscode\extensions\danielgavin.ols-0.1.3\node_modules\vscode-jsonrpc\lib\common\messageReader.js:124:42)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 5:26:26 pm] error in parse file for indexing C:/Program Files/odin-windows-amd64-dev-2022-06/core/builtin/builtin.odin
[Error - 5:26:26 pm] error in parse file for indexing C:/Program Files/odin-windows-amd64-dev-2022-06/core/intrinsics/intrinsics.odin
```

The intellisense / other features in the plugin seem to work fine.

**Comment by cshenton** [comment]
This issue turned up for me about a week or two ago and has persisted through a few odin / ols updates.

**Comment by cshenton** [comment]
Minimal repro:
```go
package main

import vk "vendor:vulkan"

main :: proc() {
    is_present: bool
    family: vk.QueueFamilyProperties
    if .GRAPHICS in family.queueFlags && is_present {
        // woops!
    }
}
```

**Comment by DanielGavin** [comment]
Fixed.
