### ISSUE TITLE
ols crashes while trying to complete certain struct literal

### ISSUE THREAD

**Issue by Despacito696969** [DanielGavin/ols#134]
```odin
package main

Thing :: struct
{
   thing2: Thing2,
}

Thing2 :: struct
{
   thing3: Thing3,
}

Thing3 :: struct
{
   very_important: f32,
}

main :: proc()
{
   thing: Thing   
   thing = Thing{
      Thing2{/*Try putting here 'T'*/},
   }
}
```

Putting a 'T' there in vscode outputs multiple times:

```
[Error - 01:14:38] Request textDocument/completion failed.
Error: Connection got disposed.
	at Object.dispose (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-jsonrpc/lib/common/connection.js:1105:27)
	at Object.dispose (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-languageclient/lib/common/client.js:163:35)
	at LanguageClient.handleConnectionClosed (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-languageclient/lib/common/client.js:2665:42)
	at LanguageClient.handleConnectionClosed (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-languageclient/lib/node/main.js:173:15)
	at closeHandler (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-languageclient/lib/common/client.js:2652:18)
	at CallbackList.invoke (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at closeHandler (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-jsonrpc/lib/common/connection.js:272:26)
	at CallbackList.invoke (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
	at Emitter.fire (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
	at StreamMessageWriter.fireClose (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:42:27)
	at Socket.<anonymous> (/home/imaginary/.vscode/extensions/danielgavin.ols-0.1.3/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:74:42)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)
```

**Comment by DanielGavin** [comment]
Should be fixed.
